### ISSUE TITLE
動態效果

### ISSUE THREAD

**Issue by JediLin** [Tofuswang/w3c-final-project#1]
響應式設計方面的瑕疵：未尊重使用者作業系統層級設定的 reduced-motion 偏好，demo site 的 banner 區強制呈現可能造成使用者頭暈跌倒的背景動態效果。

建議以 [prefers-reduced-motion](https://caniuse.com/prefers-reduced-motion) media query 實作相關的響應式設計。

**Comment by Tofuswang** [comment]
已增加對於 reduced-motion 偏好設置的支持，感謝建議！
https://w3c-final-project.vercel.app/
